---
title: Producer dependency graph
---
flowchart LR
    app_01b41d5824bc["Scheduler Agent
rev 3 / Agent" ]
    app_039ac016e589["eGovPortalCore
rev 6 / WebApplication" ]
    app_08bbebec64c0["Document Validation Agent
rev 12 / Agent" ]
    app_32a85fa9e9b7["Triage Agent
rev 2 / Agent" ]
    app_39e090e491c5["Underwriter Agent
rev 16 / Agent" ]
    app_45449aa04038["Orchestrator Agent
rev 3 / Agent" ]
    app_47ddf305c5c2["Enrichment Agent
rev 14 / Agent" ]
    app_907cc220ecb9["Intake Agent
rev 12 / Agent" ]
    app_96046015550f["Apps Common Core
rev 8 / WebApplication" ]
    app_9f8430b1c94f["Communication Agent
rev 12 / Agent" ]
    app_b3d8e8fa98b7["eGovPortal
rev 9" ]
    app_d179d8af026e["eGovPortalBackoffice
rev 6 / WebApplication" ]
    app_b3d8e8fa98b7 --> app_01b41d5824bc
    app_b3d8e8fa98b7 --> app_039ac016e589
    app_b3d8e8fa98b7 --> app_08bbebec64c0
    app_b3d8e8fa98b7 --> app_32a85fa9e9b7
    app_b3d8e8fa98b7 --> app_39e090e491c5
    app_b3d8e8fa98b7 --> app_45449aa04038
    app_b3d8e8fa98b7 --> app_47ddf305c5c2
    app_b3d8e8fa98b7 --> app_907cc220ecb9
    app_b3d8e8fa98b7 --> app_96046015550f
    app_b3d8e8fa98b7 --> app_9f8430b1c94f
    app_b3d8e8fa98b7 --> app_d179d8af026e
