[project]
name = "odc-cli"
version = "0.1.0"
description = "OutSystems ODC CLI"
readme = "README.md"
authors = [
    { name = "Tony", email = "tony.lbvre@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "python-dotenv>=1.2.2",
]

[project.scripts]
odc = "odc_cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/odc_cli"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
